### ISSUE TITLE
Hotkeys for swapping characters stop working when a certain character is active

### ISSUE THREAD

**Issue by AshtonO** [Proopai/eve-o-preview#14]
I have my settings file set to use F1-F4 to cycle through my characters, With F1 always being on my first account chars, F2 being my second account chars, etc.  This works fine when I first start Eve-O-Preview, but after swapping a few times, it suddenly will stop working whenever I switch to a certain character (usually it's the F3 character). If I manually switch back to F1, F2, or F4 characters, I can keep swapping between them fine with those keys, but as soon as I hit F3 and it switches to that character, F1, F2, and F4 no longer work to swap to another character.  It's as if Eve-O-Preview stops processing hotkeys when this character is active.

I've attached my settings file
[Eve-O Preview.json](https://github.com/user-attachments/files/17282600/Eve-O.Preview.json)

**Comment by andrewtquick** [comment]
This appears to be correct. I had this issue once before, ensure that you spelled the characters names correctly and the title for the eve clients is "EVE - Character Name"

**Comment by AshtonO** [comment]
Character names are all spelled correctly. If they weren't, then the hotkey should never work, correct? It shouldn't work fine for a few cycles and then suddenly stop working.

I did try setting keybindings to 1-4 instead of F1-F4, and these work fine with no issues. So it seems specific to using function keys.

**Comment by DalShooth** [comment]
It is important that you make sure you dont have conflicting keybinds with your OS and/or EVE. Please check and see if F3 is setup anywhere in the EVE client and your OS.

Also when you press F3, do you use lose focus on the account?

I use F3 myself and I do not have this issue.

**Comment by DalShooth** [comment]
@AshtonO Any update?

We will be releasing a new version that will be updating .NET. If what youre experiencing is a bug, it may get cleared up with the new update and code.

**Comment by AshtonO** [comment]
> @AshtonO Any update?
> 
> We will be releasing a new version that will be updating .NET. If what youre experiencing is a bug, it may get cleared up with the new update and code.

Appreciate the followup @DalShooth. So after switching back to 1-4 as the keybindings, and validating that that never causes issues, I went and reverted back to using F1-F4, and haven't seen the issue reproduce in the minimal testing I've done. I haven't had a ton of time to play with it, but at least in some initial testing I stopped seeing the issue.  I don't really understand how this would have changed anything or fixed the issue, so it's entirely possible something else was intercepting the function keys and now it's not. I did a quick audit of the programs I normally have running just to make sure nothing else might be intercepting them, and nothing turned up.

I'll let you know if I can reproduce this going forward.  Out of curiosity, is there an easy way for me to add logs and build from source if I can reliably reproduce it and want to help debug what's happening? I'm assuming key listening is happening here: https://github.com/Proopai/eve-o-preview/tree/master/src/Eve-O-Preview/Hotkeys? So I assume it would be useful to at least log when keys are intercepted there to validate whether it's a problem receiving the keystrokes, or a problem switching clients once the keystroke is received.

**Comment by DalShooth** [comment]
Im going to close this ticket for now. A new release is coming out today and its going to bring the code more up today. I would recommend downloading it when its available. If you see the issue return after, please open a new ticket.

Thanks for taking the time to come here and let us know.

**Comment by AshtonO** [comment]
Sadly this issue still reproduces for me even with the newest changes. I did some more debugging @DalShooth and found some other weird irregularities.  

1. It turns out that the F3 key specifically was a red-herring.  This appears to happen for whatever eve client was the last one to open.  More info on that at the bottom with the video and repro steps I found
2. I can get this to happen with the cycle client keybindings. When I cycle through clients, it always gets stuck on the most recently open client
3. Weirdly, when I have my mouse on anything other than the eve client, things work fine.  I tested this in three different ways: switching my client windows to a smaller size so I can hover my mouse off the client, opening the on-screen-keyboard and hovering my mouse on it, and hovering my mouse directly on the eve-o-preview frames 


I recorded a video showing the bug using the cycle keybinding, as this makes it really clear that eve-o appears to be trying to swap to the next eve client (notice the highlight around the active client keeps moving), but for some reason, it can't.  Notice in the video that if I hover my mouse over the Eve-O preview, or the on screen keyboard, cycling works fine again.  I then close my third client, which was cycling fine, and reopen it. Now, I get stuck on my third client and the fourth client, which previously had issues, cycles fine.

I'm at a loss here, and I recognize you're probably not going to be able to do much if you can't get this to reproduce locally.  FWIW, I verified my function keys are not bound on all clients, they don't seem to be bound to anything windows side, as pressing them when Eve-O is closed does nothing, and finally, if it helps, I have all of my clients set up in graphics settings to be Fixed Window, but I also tried full screen and I still see the same issue. 

Video Link: https://www.dropbox.com/scl/fi/ew3ne0vphhlzd5dimlmqs/Recording-2024-10-09-124051.mp4?rlkey=p1dcx2tspxsdgm3y5mqd99yk9&st=n72ed9rm&dl=0

**Comment by Proopai** [comment]
I know that you closed this but I see what your talking about.  I will look into seeing if i can Duplicate this issue and maybe resolve it.  Almost looks like once it gets to that account it just Gives up the list of clients open.

I am also looking to add in a Debug mode to show more behind of what its doing so when you have these issues you can report back with that log and we know where we should look and shouldn't from it.
